version: '3'

vars:
  VERSION:
    sh: cat VERSION

tasks:
  default:
    desc: Build WASM module and TypeScript
    deps: [check:all]
    cmds:
      - zig build
      - bun run build

  build:wasm:
    desc: Build WASM module
    deps: [check:all]
    cmds:
      - zig build wasm

  build:ts:
    desc: Build TypeScript app
    deps: [check:all]
    cmds:
      - bun run build

  build:server:
    desc: Build static file server
    dir: server
    cmds:
      - zig build

  run:
    desc: Build and run Tauri desktop app (release)
    cmds:
      - task: build:tauri
      - open ./src-tauri/target/release/bundle/macos/Hangul\ Typing.app

  run:dev:
    desc: Run Tauri desktop app in development mode
    dir: src-tauri
    deps: [fmt:rust, lint:rust]
    cmds:
      - cargo tauri dev

  dev:server:
    desc: Start frontend dev server for Tauri
    cmds:
      - task: default
      - task: build:server
      - cd server && zig build run -- --root ../www --port 8230

  run:web:
    desc: Start web dev server and open browser
    cmds:
      - task: default
      - task: build:server
      - |
        echo "Starting server on http://127.0.0.1:8230"
        open http://127.0.0.1:8230
        cd server && zig build run -- --root ../www --port 8230

  dev:serve:
    desc: Build all and run Zig dev server
    cmds:
      - task: default
      - task: build:server
      - cd server && zig build run -- --root ../www

  test:
    desc: Run all tests
    cmds:
      - zig build test

  check:all:
    desc: Run linting, formatting checks, and tests with coverage
    cmds:
      - bun run check:all

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf zig-out .zig-cache
      - rm -rf server/zig-out server/.zig-cache
      - rm -f www/hangul-typing.wasm

  fmt:
    desc: Format Zig source files
    cmds:
      - zig fmt src/
      - zig fmt build.zig
      - zig fmt server/src/
      - zig fmt server/build.zig

  # Tauri tasks
  fmt:rust:
    desc: Check Rust formatting
    dir: src-tauri
    cmds:
      - cargo fmt --check

  lint:rust:
    desc: Run Clippy linter on Rust code
    dir: src-tauri
    cmds:
      - cargo clippy -- -D warnings

  build:tauri:
    desc: Build Tauri desktop app for macOS (release)
    dir: src-tauri
    deps: [fmt:rust, lint:rust]
    cmds:
      - cargo tauri build

  # Release tasks
  release:patch:
    desc: Release patch version (bug fixes)
    cmds:
      - task: fmt
      - task: _bump-version
        vars: { PART: patch }

  release:minor:
    desc: Release minor version (new features)
    cmds:
      - task: fmt
      - task: _bump-version
        vars: { PART: minor }

  release:major:
    desc: Release major version (breaking changes)
    cmds:
      - task: fmt
      - task: _bump-version
        vars: { PART: major }

  _bump-version:
    internal: true
    cmds:
      - |
        current=$(cat VERSION)
        IFS='.' read -r major minor patch <<< "$current"
        case "{{.PART}}" in
          major) major=$((major + 1)); minor=0; patch=0 ;;
          minor) minor=$((minor + 1)); patch=0 ;;
          patch) patch=$((patch + 1)) ;;
        esac
        new_version="$major.$minor.$patch"
        
        # Update VERSION files
        echo "$new_version" > VERSION
        cp VERSION www/VERSION
        
        # Update Tauri config version (macOS sed)
        sed -i.bak 's/"version": "[^"]*"/"version": "'$new_version'"/' src-tauri/tauri.conf.json && rm src-tauri/tauri.conf.json.bak
        
        # Update Cargo.toml version (macOS sed)
        sed -i.bak 's/^version = "[^"]*"/version = "'$new_version'"/' src-tauri/Cargo.toml && rm src-tauri/Cargo.toml.bak
        
        # Update Cargo.lock (regenerate with new version)
        cd src-tauri && cargo update -p hangul-typing && cd ..
        
        # Stage and commit
        git add VERSION www/VERSION src-tauri/tauri.conf.json src-tauri/Cargo.toml src-tauri/Cargo.lock
        git commit -m "chore: bump version to $new_version"
        git tag -a "v$new_version" -m "Release v$new_version"
        echo "Released v$new_version"
